Repository Leo-Corporation/ColorPicker, pull requests merged in 2022-10, with the labels that each got.

#177 Updated Simplified Chinese translation
  ColorPicker/Properties/Resources.zh-CN.resx
Labels: vNext, roadmap, translation

#178 Version 4.5.0.2210
  ColorPicker.Setup/Setup.iss
  ColorPicker/Classes/Global.cs
  ColorPicker/Classes/Settings.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/Enums/ColorTypes.cs
  ColorPicker/MainWindow.xaml.cs
  ColorPicker/Pages/ConverterPage.xaml
  ColorPicker/Pages/ConverterPage.xaml.cs
  ColorPicker/Pages/PalettePage.xaml
  ColorPicker/Pages/PalettePage.xaml.cs
  ColorPicker/Pages/PickerPage.xaml.cs
  ColorPicker/Pages/SettingsPage.xaml.cs
  ColorPicker/Properties/Resources.Designer.cs
  ColorPicker/Properties/Resources.en-US.resx
  ColorPicker/Properties/Resources.fr-FR.resx
  ColorPicker/Properties/Resources.resx
  ColorPicker/Properties/Resources.zh-CN.resx
  ColorPicker/UserControls/RecentColorItem.xaml.cs
  ColorPicker/Windows/FirstRunWindow.xaml.cs
  ColorPicker/Windows/TextToolWindow.xaml
  ColorPicker/Windows/TextToolWindow.xaml.cs
Labels: enhancement, vNext, roadmap

#180 Added the Italian language
  ColorPicker/Properties/Resources.it-IT.resx
Labels: vNext, translation, hacktoberfest-accepted

#181 Version 4.5.1.2210
  ColorPicker.Setup/Setup.iss
  ColorPicker/Classes/Global.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/MainWindow.xaml
  ColorPicker/Pages/FirstRunPages/LanguagePage.xaml.cs
  ColorPicker/Pages/SettingsPage.xaml.cs
Labels: enhancement, vNext, translation
