Repository Leo-Corporation/ColorPicker, pull requests merged in 2022-01, with the labels that each got.

#97 Update license copyright year(s)
  LICENSE
Labels: documentation

#105 Version 3.9.0.2201
  ColorPicker.Setup/Setup.iss
  ColorPicker/App.xaml
  ColorPicker/Classes/Global.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/Images/ColorWheel.png
  ColorPicker/MainWindow.xaml
  ColorPicker/MainWindow.xaml.cs
  ColorPicker/Pages/PickerPage.xaml
  ColorPicker/Pages/PickerPage.xaml.cs
  ColorPicker/Pages/SettingsPage.xaml.cs
  ColorPicker/Properties/Resources.Designer.cs
  ColorPicker/Properties/Resources.en-US.resx
  ColorPicker/Properties/Resources.fr-FR.resx
  ColorPicker/Properties/Resources.resx
  ColorPicker/Properties/Resources.zh-CN.resx
  ColorPicker/Windows/ColorWheelWindow.xaml
  ColorPicker/Windows/ColorWheelWindow.xaml.cs
  ColorPicker/Windows/TextToolWindow.xaml
  ColorPicker/Windows/TextToolWindow.xaml.cs
Labels: enhancement, vNext, roadmap

#107 Update Simplified Chinese language
  ColorPicker/Properties/Resources.zh-CN.resx
Labels: vNext, translation

#108 Version 3.9.1.2201
  ColorPicker.Setup/Setup.iss
  ColorPicker/Classes/Global.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/Properties/Resources.zh-CN.resx
Labels: enhancement, vNext, translation
