Repository Leo-Corporation/ColorPicker, pull requests merged in 2025-04, with the labels that each got.

#459 Version 6.7.0.2504
  ColorPicker.Setup/Setup.iss
  ColorPicker/App.xaml
  ColorPicker/App.xaml.cs
  ColorPicker/Classes/Bookmarks.cs
  ColorPicker/Classes/Global.cs
  ColorPicker/Classes/Settings.cs
  ColorPicker/Classes/XmlSerializerManager.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/MainWindow.xaml
  ColorPicker/MainWindow.xaml.cs
  ColorPicker/Pages/AiGenPage.xaml
  ColorPicker/Pages/AiGenPage.xaml.cs
  ColorPicker/Pages/BookmarksPage.xaml.cs
  ColorPicker/Pages/ChromaticWheelPage.xaml
  ColorPicker/Pages/ChromaticWheelPage.xaml.cs
  ColorPicker/Pages/ContrastPage.xaml.cs
  ColorPicker/Pages/ConverterPage.xaml
  ColorPicker/Pages/ConverterPage.xaml.cs
  ColorPicker/Pages/GradientPage.xaml.cs
  ColorPicker/Pages/ImageExtractorPage.xaml.cs
  ColorPicker/Pages/PalettePage.xaml.cs
  ColorPicker/Pages/SelectorPage.xaml
  ColorPicker/Pages/SelectorPage.xaml.cs
  ColorPicker/Pages/SettingsPage.xaml
  ColorPicker/Pages/SettingsPage.xaml.cs
  ColorPicker/Pages/TextPage.xaml
  ColorPicker/Pages/TextPage.xaml.cs
  ColorPicker/Properties/Resources.Designer.cs
  ColorPicker/Properties/Resources.en-US.resx
  ColorPicker/Properties/Resources.fr-FR.resx
  ColorPicker/Properties/Resources.resx
  ColorPicker/Properties/Resources.zh-CN.resx
  ColorPicker/Themes/Dark.xaml
  ColorPicker/Themes/Light.xaml
  ColorPicker/UserControls/DetailsControl.xaml
  ColorPicker/UserControls/DetailsControl.xaml.cs
Labels: enhancement, vNext

#461 Create Resources.ja-JP.resx
  ColorPicker/Properties/Resources.ja-JP.resx
Labels: vNext, translation

#462 Version 6.7.1.2504
  ColorPicker.Setup/Setup.iss
  ColorPicker/App.xaml.cs
  ColorPicker/Classes/Bookmarks.cs
  ColorPicker/Classes/Global.cs
  ColorPicker/Classes/XmlSerializerManager.cs
  ColorPicker/ColorPicker.csproj
  ColorPicker/Enums/Languages.cs
  ColorPicker/Pages/AiGenPage.xaml.cs
  ColorPicker/Pages/BookmarksPage.xaml.cs
  ColorPicker/Pages/ChromaticWheelPage.xaml.cs
  ColorPicker/Pages/ContrastPage.xaml.cs
  ColorPicker/Pages/ConverterPage.xaml.cs
  ColorPicker/Pages/GradientPage.xaml.cs
  ColorPicker/Pages/PalettePage.xaml.cs
  ColorPicker/Pages/SelectorPage.xaml.cs
  ColorPicker/Pages/SettingsPage.xaml
  ColorPicker/Pages/SettingsPage.xaml.cs
  ColorPicker/Pages/TextPage.xaml.cs
  ColorPicker/Properties/Resources.ja-JP.resx
  ColorPicker/UserControls/DetailsControl.xaml.cs
  ColorPicker/Windows/ColorDetailsWindow.xaml.cs
Labels: enhancement, vNext, translation
